name: "Collect data"

on:
  push:
    branches: [ "main" ]
  schedule:
   - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Resolve domains, collect and store IP addresses
        run: |
          python -m pip install pandas requests
          python get_data.py
          git config --global user.email "alexivanelli@gmail.com"
          git config --global user.name "Alexander Ivanelli"
          git add -A
          git commit -m "Automatic update"
          git push
